from setuptools import setup, Extension

setup(
    name = 'bruce-package',
    version = '3.8',
    description = 'GPU-accelerated binary star model',
    url = None,
    author = 'Samuel Gill et al',
    author_email = 'samuel.gill@warwick.ac.uk',
    license = 'GNU',
    packages=['bruce','bruce/binarystar'],
    scripts=['Utils/ngtsfit/ngtsfit','Utils/ngtsfit/lcfit',
             'Utils/lcbin/lcbin',
             'Utils/tessget/tessget',
             'Utils/tessget/tessgetpca',
             'Utils/tessget/tessquery',
             'Utils/tessget/getall',
             'Utils/tls/tls',
             'Utils/tls/findtransit',
             'Utils/tls/PAOtls',
             'Utils/tls/mbls',
             'Utils/prewhiten/prewhiten',
             #'Utils/mbls/mbls',
             'Utils/predict/predict',
             'Utils/predict/predictedges',
             'Utils/analyse/aperturesearch',
             'Utils/analyse/templatematch',
             'Utils/analyse/analyse',
             'Utils/analyse/plot_nights',
             'Utils/massfunc/massfunc',
             'Utils/modulation/modulation',
             'Utils/modulation/PAOmod',
             'Utils/quickphot/quickphot',
             'Utils/quickphot/quickphotcube',
             'Utils/tic2wasp/tic2wasp',
             'Utils/monofind/monofind',
             'Utils/monofind/monofindSGE',
             'Utils/monofind/vet',
             'Utils/spupnic/spupnic',
             'Utils/bls/bls'],

    install_requires=['numba']
)