#!/home/sam/anaconda3/bin/python

import numba, numba.cuda 
from bruce.binarystar import lc
import numpy as np, sys, os, math
import argparse
import matplotlib
#matplotlib.use('Agg')
import matplotlib.pyplot as plt
from tqdm import tqdm
from scipy.stats import  sem
from scipy.signal import find_peaks
from scipy.optimize import minimize
import warnings 
warnings.filterwarnings('ignore')

# LC bin 
def lc_bin(time, flux, bin_width):
	'''
	Function to bin the data into bins of a given width. time and bin_width 
	must have the same units
	'''

	edges = np.arange(np.min(time), np.max(time), bin_width)
	dig = np.digitize(time, edges)
	time_binned = (edges[1:] + edges[:-1]) / 2
	flux_binned = np.array([np.nan if len(flux[dig == i]) == 0 else flux[dig == i].mean() for i in range(1, len(edges))])
	err_binned = np.array([np.nan if len(flux[dig == i]) == 0 else sem(flux[dig == i]) for i in range(1, len(edges))])
	time_bin = time_binned[~np.isnan(err_binned)]
	err_bin = err_binned[~np.isnan(err_binned)]
	flux_bin = flux_binned[~np.isnan(err_binned)]   

	return time_bin, flux_bin, err_bin


# Argument parser
parser = argparse.ArgumentParser('templatematch')
#parser.add_argument('-t', 
#                help='The transit epoch in arbritraty time units consisting with the input file.', 
#                dest="t_zero", 
#                action='store')

parser.add_argument("filename",
                    help='The filename from which to template search')

parser.add_argument('-b', 
                    '--period',
                    help='The orbital period in arbritraty time units consisting with the input file.',
                    default=10, type=float)  

parser.add_argument('-c', 
                    '--radius_1',
                    help='The radius of star 1 in units of the semi-major axis, a.',
                    default=0.2, type=float)  

parser.add_argument('-d', 
                    '--k',
                    help='The ratio of the radii of star 2 and star 1 (R2/R1).',
                    default=0.2, type=float)  
    
parser.add_argument('-e', 
                    '--b',
                    help='The impact parameter of the orbit (incl = arccos(radius_1*b).',
                    default=0., type=float)  

parser.add_argument('-f', 
                    '--light_3',
                    help='The third light.',
                    default=0.0, type=float) 

parser.add_argument('-g', 
                    '--save_path',
                    help='Tha save path directory',
                    default='.',  type=str) 


parser.add_argument('--gpu', action="store_true", default=False)
parser.add_argument('--workout', action="store_true", default=False)
parser.add_argument('--search_aliases', action="store_true", default=False)
parser.add_argument('-i', 
                    '--n_aliases',
                    help='The number of aliases to search',
                    default=10,  type=int) 

parser.add_argument('-j', 
                    '--name',
                    help='The name of the star',
                    default='star',  type=str) 

parser.add_argument('-k', 
                    '--reference_epoch',
                    help='The third light.',
                    default=-1, type=float) 

@numba.njit
def transit_width(r, k, b, P):
	"""
	Total transit duration.
	See equation (3) from Seager and Malen-Ornelas, 2003ApJ...585.1038S.
	:param r: R_star/a
	:param k: R_planet/R_star
	:param b: impact parameter = a.cos(i)/R_star
	:param P: orbital period (optional, default P=1)
	:returns: Total transit duration in the same units as P.
	"""

	return P*math.asin(r*math.sqrt( ((1+k)**2-b**2) / (1-b**2*r**2) ))/math.pi


###################################################
# Fortran conversions
###################################################
@numba.njit
def sign(a,b) : 
    if b >= 0.0 : return abs(a)
    return -abs(a)

###################################################
# Brent minimisation
###################################################
@numba.njit
def brent(x1,x2,  k, b, P, width):
    # pars
    tol = 1e-8
    itmax = 100
    eps = 1e-5

    a = x1
    b = x2
    c = 0.
    d = 0.
    e = 0.
    fa = transit_width(a, k, b,P) - width
    fb = transit_width(b, k, b,P) - width

    fc = fb

    for iter in range(itmax):
        if (fb*fc > 0.0):
            c = a
            fc = fa
            d = b-a
            e=d   

        if (abs(fc) < abs(fb)):
            a = b
            b = c
            c = a
            fa = fb
            fb = fc
            fc = fa

        tol1 = 2.0*eps*abs(b)+0.5*tol
        xm = (c-b)/2.0
        if (abs(xm) <  tol1 or fb == 0.0) : return b

        if (abs(e) > tol1 and abs(fa) >  abs(fb)):
            s = fb/fa
            if (a == c):
                p = 2.0*xm*s
                q = 1.0-s
            else:
                q = fa/fc
                r = fb/fc
                p = s*(2.0*xm*q*(q-r)-(b-a)*(r-1.0))
                q = (q-1.0)*(r-1.0)*(s-1.0)
            
            if (p > 0.0) : q = - q
            p = abs(p)
            if (2.0*p < min(3.0*xm*q-abs(tol1*q),abs(e*q))):
                e = d
                d = p/q
            else:
                d = xm
                e = d
        else:
            d = xm
            e = d   

        a = b
        fa = fb      
         
        if( abs(d) > tol1) : b = b + d
        else : b = b + sign(tol1, xm)

        fb = transit_width(b, k, b,P) - width
    return 1



def min_func(theta, t, LC_model, period_new, ret = False  ):
    ff = np.abs(lc(t, radius_1 = theta[0], k = theta[1], incl=theta[2], period=period_new) - LC_model)

    if ret : return ff
    else : return np.sum(ff)




def match_transit_paramaters_to_period(radius_1, k ,incl, period_old, period_new):
    # First, get the transit width
    b = np.cos(incl) / radius_1 
    width = transit_width(radius_1, k, b, P=period_old)
    #print('b = {:}, width = {:}, incl = {:}'.format(b, width, incl))

    # Now create the model to be optimised over 
    t = np.linspace(-width, width, 10000)
    LC_model = lc(t, radius_1=radius_1, k=k, incl = 180*incl/np.pi, period=period_old)
    #plt.plot(t, LC_model)
    #plt.show()


    # Now minimize
    theta = [0.001, k, 89.]
    res = minimize(min_func, theta, method='L-BFGS-B', bounds = [[0.0001,0.8],[0.0001,0.8], [80,90.]], args = (t, LC_model, period_new))
    return res


def min_func2(theta, t, LC_model, period_new, ret = False  ):
	incl = 180*np.arccos(theta[2]*theta[0])/np.pi
	ff = np.abs(lc(t, radius_1 = theta[0], k = theta[1], incl=incl, period=period_new) - LC_model)

	if ret : return ff
	else : return np.sum(ff)

def match_transit_paramaters_to_period2(radius_1, k ,b, period_old, period_new):
    # First, get the transit width
    incl = 180*np.arccos(b*radius_1)/np.pi
    width = transit_width(radius_1, k, b, P=period_old)
    #print('b = {:}, width = {:}, incl = {:}'.format(b, width, incl))

    # Now create the model to be optimised over 
    t = np.linspace(-width, width, 10000)
    LC_model = lc(t, radius_1=radius_1, k=k, incl = incl, period=period_old)
    #plt.plot(t, LC_model)
    #plt.show()


    # Now minimize
    theta = [0.005, k, 89.]
    res = minimize(min_func2, theta, method='L-BFGS-B', bounds = [[0.001,0.8],[0.001,0.8], [0, 1+k]], args = (t, LC_model, period_new), options = {'eps' : 0.001})
    return res




if __name__=="__main__":
	# First, parse the args
	args = parser.parse_args()

	# First, load the lightcurve
	try    :	time, mag, mag_err = np.loadtxt(args.filename).T
	except :	
		try : time, mag, mag_err, flux, flux_err = np.loadtxt(args.filename).T
		except : 
			time, mag = np.loadtxt(args.filename).T
			mag_err = np.ones(len(time))*1e-3
	#finally:	raise IOError('Unable to find or read file: {:}'.format(args.filename))

	args.filename = args.filename[3:]


	# Now sort the lightcurve and ensure f32
	sort = sorted(zip(time, mag, mag_err))
	time = np.array([i[0] for i in sort], dtype = np.float64)
	mag = np.array([i[1] for i in sort], dtype = np.float64)
	mag_err = np.array([i[2] for i in sort], dtype = np.float64)

	# Now calculate a weighted mean
	weighted_mean = np.median(mag)


	# First, check aliases
	if args.search_aliases:
		# Set the TSP 
		os.system('tsp -S 4') # use the gpu ;) 



		# make the directories 
		for i in range(1, args.n_aliases+1):
			# First, we need to match parameters for orbital period 1
			res = match_transit_paramaters_to_period(args.radius_1, args.k ,np.arccos(args.radius_1*args.b), args.period, args.period/i)
			#print(res)

			# Make the directory
			#print(args.period, i, args.period / i)
			os.system('mkdir -p {:}/tls_aliases/{:.2f}'.format(args.save_path, args.period/i))

			# Clean the directory
			os.system('rm -f {:}/tls_aliases/{:.2f}/*'.format(args.save_path, args.period/i))

			# now get save the data file
			phase = ((time - 0) / (args.period / i)) - np.floor((time - 0) / (args.period / i))
			phase = np.concatenate((phase-1, phase))
			mag_ = np.concatenate((mag, mag))
			mag_err_ = np.concatenate((mag_err, mag_err))

			sort = sorted(zip(phase, mag_, mag_err_))
			phase = np.array([j[0] for j in sort])*(args.period / i)
			mag_ = np.array([j[1] for j in sort])
			mag_err_ = np.array([j[2] for j in sort])

			tmp = np.array([phase.tolist(), mag_.tolist(), mag_err_.tolist()]).T 
			np.savetxt('{:}/tls_aliases/{:.2f}/{:}_phased.dat'.format(args.save_path, args.period/i, args.name), tmp) 

			# Now make the call 
			cmd = 'tsp tls {:}/tls_aliases/{:.2f}/{:}_phased.dat --period {:} --radius_1 {:} --k {:} --b {:} --save_path {:}/tls_aliases/{:.2f} --gpu'.format(args.save_path, args.period/i, args.name, args.period/i,   res.x[0], res.x[1], np.cos(np.pi*res.x[2]/180) / res.x[1], args.save_path, args.period/i)
			print(cmd)
			#os.system('tsp {:}'.format(cmd))

		exit()


	# Now we need to pad the data set using the standard deviation of the first 12 hours of data
	time_start_pad = time[time < (time[0] + 0.5)]  - 1
	mag_start_pad = np.random.normal(weighted_mean, np.std(mag), time_start_pad.shape[0])                  # mag[time < (time[0] + 0.5)]
	mag_err_start_pad = np.random.uniform(mag_err.min(), mag_err.max(), time_start_pad.shape[0]) # mag_err[time < (time[0] + 0.5)]

	time_end_pad = time[time > (time[-1] - 0.5)] + 1
	mag_end_pad = np.random.normal(weighted_mean, np.std(mag), time_end_pad.shape[0])                      # mag[time > (time[-1] - 0.5)]
	mag_err_end_pad = np.random.uniform(mag_err.min(), mag_err.max(), time_end_pad.shape[0])   # mag_err[time > (time[-1] - 0.5)]

	time = np.concatenate((time_start_pad, time, time_end_pad))
	mag = np.concatenate((mag_start_pad, mag, mag_end_pad))
	mag_err = np.concatenate((mag_err_start_pad, mag_err, mag_err_end_pad))



	# now bin to 30 mins 
	#_time, _mag, _mag_err = lc_bin(time, mag, 0.1/24)

	# Now Create time axis for models to be sampled at. 
	# This is required to catch ingress/egress events at the star/end of nights
	dt = 0.1/24
	time_models = np.arange(time[0], time[-1], dt)
	dChi = np.empty(time_models.shape[0])

	# Now save the figure
	plt.figure(figsize=(15,5))
	plt.scatter(time, mag, c='k', s=10)
	plt.axhline(weighted_mean, ls='--', c='r')
	plt.gca().invert_yaxis()
	plt.xlabel('Time')
	plt.ylabel('Mag')
	plt.savefig('{:}/{:}_weighted_mean.pdf'.format(args.save_path, args.name))
	plt.close()

	# Now put onto the GPU if needed and create the relevant arrays
	if args.gpu:
		time_    = numba.cuda.to_device(time)
		mag_     = numba.cuda.to_device(mag)
		mag_err_ = numba.cuda.to_device(mag_err)

	# Now get the transit width
	width = transit_width(args.radius_1, args.k, args.b, P=args.period)
	print('Transit width = {:.2f} hrs'.format(width * 24.))

	# Now create the template
	incl = 180*np.arccos(args.radius_1*args.b)/np.pi
	time_template = np.linspace(-width, width, 100)
	mag_template = weighted_mean - 2.5*np.log10(lc(time_template, period = args.period, radius_1 = args.radius_1, k = args.k, incl = incl))
	template_depth = np.max(mag_template) - np.min(mag_template)

	plt.figure(figsize=(15,5))
	plt.plot(time_template, mag_template, 'r')
	plt.xlabel('Time from epoch [d]')
	plt.ylabel('Mag')
	plt.gca().invert_yaxis()
	plt.savefig('{:}/{:}_template.png'.format(args.save_path, args.name))
	plt.close()

	# Now get the reference logl-likliehood
	if args.gpu : reference_loglike = lc(time_, mag_, mag_err_, J=0,incl = 40., zp=weighted_mean, gpu=1, ld_law_1=-2)
	else        : reference_loglike = lc(time, mag, mag_err, J=0,incl = 40., zp=weighted_mean, ld_law_1=-2)
	print('Reference log-likliehood = {:.2f}'.format(reference_loglike))

	# Now enter the main loop
	if args.gpu:
		for i in tqdm(range(time_models.shape[0])) : dChi[i] = lc(time_, mag_, mag_err_, J=0,incl = incl, zp=weighted_mean, gpu=1,
										radius_1 = args.radius_1, k = args.k, t_zero = time_models[i], period = args.period, ld_law_1=-2) - reference_loglike
	else :
		for i in tqdm(range(time_models.shape[0])) : dChi[i] = lc(time, mag, mag_err, J=0,incl = incl, zp=weighted_mean,
										radius_1 = args.radius_1, k = args.k, t_zero = time_models[i], period = args.period, ld_law_1=-2) - reference_loglike
	height=80
	height=1

	f, (ax1,ax2) = plt.subplots(nrows=2, ncols=1, figsize=(15,8), sharex=True)
	ax1.plot(time_models, dChi, c='k')
	ax1.set_ylim(0, None)
	ax1.set_ylabel(r'$\Delta \mathcal{L}$')
	ax1.grid()
	ax1.axhline(height, c='k', ls='--')
	ax2.scatter(time, mag, c='k', s=10)
	ax2.invert_yaxis()
	ax2.set_ylabel('Mag')
	ax2.set_xlabel('Time [jd]')
	ax2.grid()

	np.save('dChi', np.array([time_models, dChi]))

	# Now run a peak finding algorithm
	peaks, meta = find_peaks(dChi, distance=50, height = height)
	print('Number of peaks : {:}'.format(len(peaks)))
	if len(peaks) > 10 :
		print('\tKeeping only the best 10')
		height_best_idx = meta['peak_heights'].argsort()[-10:][::-1]
		peaks = peaks[height_best_idx]

	ax1.plot(time_models[peaks], dChi[peaks], "x")
	plt.savefig('{:}/{:}_dChi.png'.format(args.save_path, args.name))


	for i in range(len(peaks)):
		t_temp = time[(time > (time_models[peaks[i]] - min(width,0.4))) & (time < (time_models[peaks[i]] + min(width,0.4)))] - time_models[peaks[i]]
		m_temp = mag[(time > (time_models[peaks[i]] - min(width,0.4))) & (time < (time_models[peaks[i]] + min(width,0.4)))]
		f = plt.figure(figsize = (15,5))
		plt.scatter(t_temp, m_temp, s=10,c='k')
		plt.plot(time_template, mag_template, 'r')
		t_temp_bin, m_temp_bin, _ = lc_bin(t_temp, m_temp, dt)
		plt.plot(t_temp_bin, m_temp_bin, 'b-', alpha = 0.5)
		#plt.gca().invert_yaxis()
		plt.ylim(weighted_mean +2.5*template_depth,weighted_mean-1.5*template_depth)
		plt.xlabel('Time - {:}'.format(time_models[peaks[i]]))
		plt.ylabel('Mag')
		plt.grid()
		plt.tight_layout()
		plt.savefig('{:}/{:}_peak{:}.pdf'.format(args.save_path,args.name, i+1))
		plt.close()


	if args.workout:
		# Create peak array
		peak_diff = np.zeros((len(peaks), len(peaks)))
		times =  time_models[peaks] 
		for i in range(len(peaks)):
			for j in range(len(peaks)):
				peak_diff[i,j] = max(times[j], times[i]) - min(times[j], times[i])

		diffs = np.sort(np.unique(peak_diff.flatten() ))[::-1][:-1]
		print('--------------------------------------------')
		print('\nThe unique differences are :')
		for i in diffs : print('\t{:.5f} days'.format(i))
		print('--------------------------------------------')
		for i in range(diffs.shape[0]):
			target_period = diffs[i] 
			multiples = []
			for j in range(i+1, diffs.shape[0]):
				ratio = (diffs[j] / diffs[i]) - np.floor(diffs[j] / diffs[i])
				if ratio > 0.5 : ratio -= 1 
				if (abs(ratio) < 0.2): multiples.append([diffs[j], abs(ratio)*24])
			if len(multiples) > 0 : print('{:.5f} could be multiples of '.format(target_period) + ' , '.join([ '{:.5f} [{:.2f} hrs]'.format(j[0],j[1]) for j in  multiples ]))
		print('--------------------------------------------')
		print('Making plots for each period at their respective epochs')

		for diff in diffs:
			mask = np.where(peak_diff==diff)
			idxs = []
			for i in mask : 
				idxs.append(i[0])
				idxs.append(i[1])
			t_zeros = np.sort(np.unique(times[np.array(idxs)]))

			# Now we have epochs and periods, lets make the plots

			for i in t_zeros:
				if args.reference_epoch != -1:
					phase_check = ((i - args.reference_epoch) / diff) - np.floor((i - args.reference_epoch) / diff)
					if phase_check > 0.5 : phase_check -= 1
					if abs(phase_check) < 0.05 : test = 1
					else : test = 0
					print('T0 : {:.6f}   period {:.6f} PHASE {:} Use : {:}'.format(diff, i, phase_check, test ))

				else : test = 1
				if test:
					print('PHASE CHECK ', phase_check)
					plt.close()
					phase = ((time - i) / diff) - np.floor((time - i) / diff)
					phase = np.concatenate((phase-1, phase))
					mag__ = np.concatenate((mag,mag))
					sort = sorted(zip(phase, mag__))
					phase = np.array([i[0] for i in sort])
					mag__ = np.array([i[1] for i in sort])
					phase_, mag___, sss = lc_bin(phase, mag__, 0.1/24/diff)
					plt.figure(figsize=(15,5))
					plt.scatter(phase, mag__, c='k', s=10, alpha = 0.3)
					plt.scatter(phase_, mag___, c='b', s=15)

					radius_1_ = brent(0.001,0.8,  args.k, args.b, diff, width)

					res = match_transit_paramaters_to_period2(args.radius_1, args.k ,args.b, args.period, diff)
					new_width = transit_width(res.x[0], res.x[1], res.x[2], 1.)
					p_ = np.linspace(-new_width,new_width,100000)
					incl = 180*np.arccos(res.x[0]*res.x[2])/np.pi
					print(res.x, new_width,incl)
					plt.plot(p_, weighted_mean-2.5*np.log10(lc(p_, radius_1 = res.x[0], k = res.x[1], incl =incl, zp = 0.)), 'r')

					plt.xlim(-new_width, new_width)
					plt.ylim(weighted_mean +2.5*template_depth,weighted_mean-1.5*template_depth)
					plt.savefig('{:}/{:}_{:}_phased.pdf'.format(args.save_path, i, diff))

