#!/home/sam/anaconda3/bin/python

###########################################################################
#                              Imports                                    #
###########################################################################

from bruce.binarystar.lc import lc, _lc
import emcee, corner, sys, os, numpy as np, math
import matplotlib.pyplot as plt 
import argparse 
from multiprocessing import Pool
from celerite.modeling import Model
from celerite import terms, GP
from scipy.stats import chisquare, sem
import matplotlib.cm as cm
import matplotlib.gridspec as gridspec
from multiprocessing import Pool
import numba
from scipy.optimize import minimize
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter,
                               AutoMinorLocator)
np.warnings.filterwarnings('ignore')
import matplotlib
#matplotlib.use('Agg')
from lightkurve.lightcurve import TessLightCurve
from scipy.signal import find_peaks, medfilt
from scipy.optimize import curve_fit
from scipy.optimize import minimize
from astropy.table import Table
import emcee ,corner, time as time_func
import flock

from lmfit import minimize, Parameters, Minimizer, printfuncs, conf_interval
import lmfit 

from scipy.stats import median_absolute_deviation

plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams.update({'font.size': 15})


###########################################################################
#                              Handy functions                            #
###########################################################################

def lc_bin(time, flux, bin_width):
        '''
        Function to bin the data into bins of a given width. time and bin_width 
        must have the same units
        '''
        
        edges = np.arange(np.min(time), np.max(time), bin_width)
        dig = np.digitize(time, edges)
        time_binned = (edges[1:] + edges[:-1]) / 2
        flux_binned = np.array([np.nan if len(flux[dig == i]) == 0 else flux[dig == i].mean() for i in range(1, len(edges))])
        err_binned = np.array([np.nan if len(flux[dig == i]) == 0 else sem(flux[dig == i]) for i in range(1, len(edges))])
        time_bin = time_binned[~np.isnan(err_binned)]
        err_bin = err_binned[~np.isnan(err_binned)]
        flux_bin = flux_binned[~np.isnan(err_binned)]   
        
        return time_bin, flux_bin, err_bin

def transit_width(r, k, b, P=1, arr=False):
    """
    Total transit duration.
    See equation (3) from Seager and Malen-Ornelas, 2003ApJ...585.1038S.
    :param r: R_star/a
    :param k: R_planet/R_star
    :param b: impact parameter = a.cos(i)/R_star
    :param P: orbital period (optional, default P=1)
    :returns: Total transit duration in the same units as P.
    """
    width = P*np.arcsin(r*np.sqrt( ((1+k)**2-b**2) / (1-b**2*r**2) ))/np.pi
    if arr : width[np.isnan(width) | np.isinf(width)] = 0.05
    else : 
        if np.isnan(width) or np.isinf(width) : width = 0.05
    return width




description = '''A program to fit binary star observations elegantly. 
Use the -h flag to see all available options for the fit. For any questions, 
please email samuel.gill@warwick.ac.uk'''

emcee_message = '''---------------------------------------------------
-                   emcee                         -
---------------------------------------------------'''

###########################################################################
#                              Arg parser                                 #
###########################################################################

# Argument parser
parser = argparse.ArgumentParser('ngtsfit', description=description)

parser.add_argument("filename",
                    help='The filename of the star (time, mag, mag_err)')

parser.add_argument('--flatten', action="store_true", default=False)

parser.add_argument('--fit_box', action="store_true", default=False)
parser.add_argument('--fit_transit', action="store_true", default=False)
parser.add_argument('--fits', action="store_true", default=False)
parser.add_argument('--check_asteroid', action="store_true", default=False)

parser.add_argument('-a', 
                '--threads',
                help='The number of threads to use [default 1]',
                default=10, type=int)

parser.add_argument('-b', 
                '--fit_period',
                help='The period to fit',
                default=30, type=float)

parser.add_argument('-c', 
                '--saveplace',
                help='The place to save',
                default='.', type=str)

parser.add_argument('-d', 
                '--R1',
                help='The radius of the primary',
                default=-99., type=float)


parser.add_argument('-e', 
                '--write_to_file',
                help='Write results to text file',
                default='no', type=str)

parser.add_argument('-f', 
                '--lock_file',
                help='The lock file',
                default='.monolock', type=str)

parser.add_argument('-g', 
                '--name',
                help='The lname',
                default='Star', type=str)

parser.add_argument('-i', 
                '--mask',
                help='The mask',
                default='no', type=str)

parser.add_argument('-j', 
                '--fitsapp',
                help='The fits aperture',
                default=2, type=int)

parser.add_argument('-k', 
                '--flatten_kernel',
                help='The kernel to flatten to',
                default=91, type=int)

parser.add_argument('-l', 
                '--ra',
                help='The target ra',
                default=-99, type=float)

parser.add_argument('-m', 
                '--dec',
                help='The target dec',
                default=-99, type=float)

parser.add_argument('-n', 
                '--mag',
                help='The target Mag',
                default=-99, type=float)

parser.add_argument('-o', 
                '--JH',
                help='The J-H color for getting R1',
                default=-99, type=float)

parser.add_argument('-p', 
                '--JHfile',
                help='The J-H file for linking J-H to R1',
                default='no', type=str)

parser.add_argument('-q', 
                '--cadence',
                help='The cadence of observations',
                default=-1, type=float)

###########################################################################
#                              The transit model                          #
###########################################################################
# Define the model
transit_model_bounds = dict(radius_1 = (0, 0.9), k = (0, 0.9), b = (0,2), fs = (-1,1), fc = (-1,1), SBR = (0,1), light3 = (0, None), J = (0, None))

class transitmodel(Model):
    parameter_names = ("t_zero", "period", "radius_1", "k", "fs", "fc", "b", "q", "albedo", "A_doppler",
                        "spots", "omega_1", "ldc_law_1","h1", "h2", "gdc_1",
                        "SBR", "light_3", "E_tol" , "zp", "J" , "cadence", "noversample")

    def get_value(self, t):
        ldc_1_1 =  1 - self.h1 + self.h2
        ldc_1_2 =   np.log2( ldc_1_1 / self.h2)
        return self.zp - 2.5*np.log10(lc(t, t_zero = self.t_zero, period = self.period,
                radius_1 = self.radius_1, k=self.k, 
                fs = self.fs, fc = self.fc, 
                q=self.q, albedo = self.albedo,
                A_doppler=self.A_doppler,
                spots = np.array(self.spots), omega_1=self.omega_1,
                incl = 180*np.arccos(self.radius_1*self.b)/np.pi,
                ld_law_1=int(self.ldc_law_1), ldc_1_1 = ldc_1_1, ldc_1_2 = ldc_1_2, gdc_1 = self.gdc_1,
                SBR=self.SBR, light_3 = self.light_3,
                E_tol=self.E_tol,
                cadence = self.cadence, noversample = self.noversample))



    def get_log_prob_prior(self, h1_ref, h2_ref):
        return -0.5*( ((self.h1 - h1_ref)**2)/(0.003**2) +     ((self.h2 - h2_ref)**2)/(0.046**2)    )

    def log_likelihood(self, t, mag, mag_err, h1_ref, h2_ref):
        ldc_1_1 =  1 - self.h1 + self.h2
        ldc_1_2 =   np.log2( ldc_1_1 / self.h2)
        llike =  lc(t, mag, mag_err, t_zero = self.t_zero, period = self.period,
                radius_1 = self.radius_1, k=self.k, zp = self.zp,
                fs = self.fs, fc = self.fc, 
                q=self.q, albedo = self.albedo,
                A_doppler=self.A_doppler,
                spots = np.array(self.spots), omega_1=self.omega_1,
                incl = 180*np.arccos(self.radius_1*self.b)/np.pi,
                ld_law_1=int(self.ldc_law_1), ldc_1_1 = ldc_1_1, ldc_1_2 = ldc_1_2, gdc_1 = self.gdc_1,
                SBR=self.SBR, light_3 = self.light_3,
                E_tol=self.E_tol,
                cadence = self.cadence, noversample = self.noversample)


        lp = llike + self.get_log_prob_prior(h1_ref, h2_ref)
        if np.isnan(lp) : return -np.inf 
        else : return lp


    def check_lims(self, t_zero_ref, period_ref):
        if (self.t_zero < t_zero_ref - 0.1*period_ref) or (self.t_zero > t_zero_ref + 0.1*period_ref) : return -np.inf
        if (self.period < period_ref - 1e-2) or (self.period > period_ref + 1e-2) : return -np.inf 
        if (self.k < 0.0) or (self.k > 0.8) : return -np.inf 
        if (self.radius_1 < 0.0) or (self.radius_1 > 0.8) : return -np.inf 
        if (self.b < 0) or (self.b > 1.0 + self.k) : return -np.inf 
        if (self.J < 0) : return -np.inf 
        if (self.q < 0) : return -np.inf 
        if (self.zp < -20) or (self.zp > 20) : return -np.inf 
        if (self.fs < -0.7) or (self.fs > 0.7) : return -np.inf 
        if (self.fc < -0.7) or (self.fc > 0.7) : return -np.inf 
        if ((self.fc**2 +  self.fs**2) > 0.999) : return -np.inf 
        if (self.SBR < 0) or (self.SBR > 1) : return -np.inf 
        return 0.

    def get_residuals(self, pars, time, mag, mag_err, theta_names, return_model = False ):
        for i in range(len(theta_names)) : self.set_parameter(theta_names[i], float(pars[theta_names[i]].value))
        if return_model : return self.get_value(time)
        else:
            residuals = (mag - self.get_value(time))**2 / (mag_err**2)
            return residuals 

    def get_box_residuals(seld, pars, time, mag, mag_err, return_model = False):
        model = np.zeros(time.shape[0])
        model[(time > (pars['box_center'].value - pars['box_width'].value/2)) & (time < (pars['box_center'].value + pars['box_width'].value/2))] = pars['box_depth'].value
        if return_model : return model 
        else: return (mag - model)**2 / mag_err**2





if __name__=="__main__":
    # First, parse the args 
    args = parser.parse_args()

    ###########################################################################
    #                 Use JH colors to get R1 where possible                  #
    ###########################################################################
    JH_flag = False
    if (args.R1==-99.) and (args.JHfile!='no') and (args.JH!=-99.0):
        print('Re-interpolating the radius from JH colors')

        # Load the table
        t = Table.read(args.JHfile, format='csv')

        # mask out bad values
        mask = (np.array(t['J-H'])=='.....') | (np.array(t['J-H'])=='...') | (np.array(t['R_Rsun'])=='...')

        # Now re interpolate
        sort = sorted(zip(np.array(t['J-H'])[~mask].tolist(), t['R_Rsun'][~mask].tolist() ))
        t['J-H'][~mask] = np.array([i[0] for i in sort])
        t['R_Rsun'][~mask] = np.array([i[1] for i in sort])

        args.R1 = np.interp(args.JH,    np.array(t['J-H'])[~mask].astype(np.float),    np.array(t['R_Rsun'])[~mask].astype(np.float), left = -99., right = -99. )

        print('J-H = {:.3f} -> R1 = {:.2f}'.format(args.JH ,args.R1))
        if (args.R1 != -99.) :  JH_flag = True

    ###########################################################################
    #                              Load the data                              #
    ###########################################################################
    if args.fits : 
        t = Table.read(args.filename)
        mask = t['DQUALITY'] == 0
        time = np.array(t['BJD'], dtype = np.float64)
        flux = t['AP{:}'.format(args.fitsapp)] - t['SKY{:}'.format(args.fitsapp)]
        mask = mask | np.isnan(-2.5*np.log10(flux)) | np.isinf(-2.5*np.log10(flux))


        t = Table.read(args.filename)[mask]
        time = np.array(t['BJD'], dtype = np.float64)
        flux = t['AP{:}'.format(args.fitsapp)] - t['SKY{:}'.format(args.fitsapp)]
        mag = np.array(-2.5*np.log10(flux), dtype = np.float64)
        mag_err = 1e-3*np.ones(len(flux), dtype = np.float64)

        # For asteroid checking
        table_asteroid = Table.read(args.filename)[mask]
    else : time, mag, mag_err = np.loadtxt(args.filename).T 

    flux = 10**(-0.4*mag)

    ###########################################################################
    #                              mask data points                           #
    ###########################################################################
    if args.mask != 'no':
        t = Table.read(args.mask)
        mask = np.zeros(len(time), dtype = np.bool)
        for i in range(len(t)):
            for j in range(len(time)):
                if abs(t['BJD'][i] - time[j]) < (0.25/24) : mask[j] = True 
        time = time[~mask]
        mag = mag[~mask]
        #mag_old = mag_old[~mask]
        mag_err = mag_err[~mask]
        flux = flux[~mask]

        # For asteroid checking
        table_asteroid = table_asteroid[~mask]

    mag_old = np.copy(mag) - np.median(mag) - 0.03


    def floating_median(x,y, boxsize):
        idx = x.argsort()
        newy = np.zeros(len(y))
        for i in range(len(y)):
            j = idx[i]
            newy[j] = np.nanmedian(y[idx[max(0,i-boxsize):min(len(y),i+boxsize)]])
        return(newy)

    

    ###########################################################################
    #                             Flatten if needed                           #
    ###########################################################################
    if args.flatten:
        mag_medfilt = np.copy(mag)

        # Find splits where at least 5 points are missing 
        cadence = 1/24
        splits = [] 
        for i in range(len(time)-1):
            if (time[i] - time[i-1]) > (5*cadence) : splits.append(i)
        nsegs = len(splits) + 1
        binned_idxs = np.array([])
        for i in range(nsegs):
            if nsegs == 1:
                idx = np.arange(0, len(time))
            else:
                if i==0 : idx = np.arange(0, splits[0])
                elif (i==(nsegs-1)) : idx = np.arange(splits[-1], len(time))
                else : idx = np.arange(splits[i-1], splits[i])

            flux_medfilt = floating_median(np.arange(idx.shape[0]),flux[idx], args.flatten_kernel)
            flux_medfilt[:20] = flux[idx][:20]
            flux_medfilt[-20:] = flux[idx][-20:]
            flux[idx] = flux[idx] / flux_medfilt
            mag_medfilt[idx] = -2.5*np.log10(flux_medfilt) - np.median(mag) - 0.03
            binned_idxs = np.concatenate((binned_idxs,idx[:20] ))
            binned_idxs = np.concatenate((binned_idxs,idx[-20:] ))

        # now clean up
        flux = np.delete(flux, binned_idxs)
        time = np.delete(time, binned_idxs)
        mag_medfilt = np.delete(mag_medfilt, binned_idxs)
        mag_err = np.delete(mag_err, binned_idxs)
        mag_old = np.delete(mag_old, binned_idxs)


        # Conver to mag 
        mag = -2.5*np.log10(flux)

    ###########################################################################
    #                              Peak finding algorithm                     #
    ###########################################################################
    height = 5*np.std(mag)
    height = median_absolute_deviation(mag)*6
    peaks, meta = find_peaks(mag, height=height, distance = 12*2)

    ###########################################################################
    #        Check that at least 3 points above threshold per peak            #
    ###########################################################################
    dele = []
    for i in range(len(peaks)):
        if (mag[peaks[i]-1] < height) or (mag[peaks[i]+1] < height) : dele.append(i)
    peaks = np.delete(peaks, dele)
    meta['peak_heights'] = np.delete(meta['peak_heights'], dele)


    ###########################################################################
    #                          Sort the peaks                                 #
    ###########################################################################
    height_best_idx = meta['peak_heights'].argsort()[::-1]
    peaks = peaks[height_best_idx]
    peaks = peaks[:5] 
    print('Number of peaks found : ', len(peaks))
    if len(peaks)==0 : exit() 



    ###########################################################################
    #                     Create the axis                                    #
    ###########################################################################
    if args.flatten :     f, axs = plt.subplots(nrows=len(peaks)+2, ncols=1, figsize=(10,15*len(peaks)))
    else :                f, axs = plt.subplots(nrows=len(peaks)+1, ncols=1, figsize=(10,15*len(peaks)))

    time_offset = int(np.min(time))
    medd = np.median(mag)
    stdd_ = np.max(mag[peaks]) #np.std(mag)

    if args.flatten:
        axs[0].scatter(time-time_offset, mag_old, c='k', s=3)
        axs[0].scatter(time-time_offset, mag_medfilt, c='y', s = 5, alpha = 0.8)
        axs[1].scatter(time-time_offset, mag, c='k', s=3)
        axs[1].plot(time-time_offset, mag, 'k', linewidth=0.5)
        axs[0].invert_yaxis()
        axs[1].invert_yaxis()
        idx_offset = 1
        axs[1].set_ylim(medd + 1.25*stdd_, medd - 0.5*stdd_)

    else:
        axs[0].scatter(time-time_offset, mag, c='k', s=3)
        axs[0].plot(time-time_offset, mag, 'k', linewidth=0.5)   
        axs[0].invert_yaxis()
        axs[0].set_ylim(medd + 1.25*stdd_, medd - 0.5*stdd_)

        idx_offset = 0


    axs[0].set(xlabel = 'BJD - {:}'.format(time_offset), ylabel = 'Mag')
    axs[1].set(xlabel = 'BJD - {:}'.format(time_offset), ylabel = 'Mag')
    axs[0+idx_offset].axhline(height, ls='--', c='k')


    # Now plot peaks 
    for i in range(len(peaks)):
        axs[0+idx_offset].scatter(time[peaks[i]]-time_offset, mag[peaks[i]], facecolors='none', edgecolors='r', s=150)
        axs[0+idx_offset].text(time[peaks[i]]-time_offset + 1, mag[peaks[i]], 'Peak {:}'.format(i+1))

    # Now plot data on axis
    for i in range(len(peaks)):
        axs[i+idx_offset+1].set_ylabel('Peak {:}'.format(i+1))
        axs[i+idx_offset+1].scatter(time-time_offset, mag, c='k', s=5)
        axs[i+idx_offset+1].plot(time-time_offset, mag, 'k', linewidth=0.5)
        axs[i+idx_offset+1].set(xlabel = 'BJD - {:}'.format(time_offset), ylabel = 'Mag', xlim=(time[peaks[i]]-0.5, time[peaks[i]]+1), ylim=(medd + 1.25*stdd_, medd - 0.5*stdd_))

    ###########################################################################
    #                              Initialse the transit model                #
    ###########################################################################
    transit_model_bounds = dict(radius_1 = (0, 0.9), k = (0, 0.9), b = (0,2), fs = (-1,1), fc = (-1,1), SBR = (0,1), light3 = (0, None), J = (0, None))
    transit_model = transitmodel(t_zero = 0., period = args.fit_period, radius_1 = 0.1, k=0.1, 
                                fs=0.,fc = 0., b = 0.2, q = 0., albedo = 0., A_doppler = 0.,
                                spots=  np.array([0.]), omega_1=1.0, ldc_law_1 = 2,
                                h1 = 0.7, h2 =0.4, gdc_1 = 0., SBR  = 0., 
                                light_3 = 0., 
                                E_tol = 1e-4, zp = 0., bounds=transit_model_bounds, J=0., 
                                cadence=args.cadence, noversample=9)


    ###########################################################################
    #                              Box fit                                    #
    ###########################################################################
    box_pars = []
    if args.fit_box:
        for i in range(len(peaks)):
            ###########################################################################
            #               Create the parameters                                     #
            ###########################################################################
            params = Parameters()
            params.add('box_center', vary=True, value=time[peaks[i]],     min=time[peaks[i]] - 0.4, max=time[peaks[i]] + 0.4)
            params.add('box_width',vary=True,   value=0.3, min=0.04, max=1)
            params.add('box_depth',vary=True,   value=0.15, min=0.001, max=1)

            mask = (time > (time[peaks[i]] - 0.75) ) & (time < (time[peaks[i]] + 0.75) )

            ###########################################################################
            #               Now solve                                                 #
            ###########################################################################
            mini = Minimizer(transit_model.get_box_residuals, params, fcn_args=(time[mask], mag[mask], mag_err[mask], False))
            lmfit_minimize_result = mini.minimize(method='differential_evolution')
            printfuncs.report_fit(lmfit_minimize_result, min_correl=0.5)

            ###########################################################################
            #               Now plot                                                  #
            ###########################################################################
            model = transit_model.get_box_residuals(lmfit_minimize_result.params, time[mask], mag[mask], mag_err[mask], True)
            axs[i+idx_offset+1].plot(time[mask]-time_offset, model, 'r', zorder=0)
            axs[i+idx_offset+1].set_xlim(lmfit_minimize_result.params['box_center'].value - 2*lmfit_minimize_result.params['box_width'].value-time_offset, lmfit_minimize_result.params['box_center'].value + 2*lmfit_minimize_result.params['box_width'].value-time_offset)
            box_pars.append([lmfit_minimize_result.params['box_center'].value, lmfit_minimize_result.params['box_width'].value, lmfit_minimize_result.params['box_depth'].value])

            R2 = np.sqrt(lmfit_minimize_result.params['box_depth'].value)*args.R1
            axs[i+idx_offset+1].set_title('R2 = {:.2f} R'.format(R2) + r'$_{\odot}$' + '\n    = {:.2f} R'.format(R2*9.73115873) + r'$_{J}$', y=1-0.2)


    ###########################################################################
    #                              Transit fit                                #
    ###########################################################################
    fit_pars = []
    ASTEROID_CHECK_1, ASTEROID_CHECK_2 = 0, 0
    X, Xst, Y, Yst, = -99*np.ones(len(peaks)),-99*np.ones(len(peaks)),-99*np.ones(len(peaks)),-99*np.ones(len(peaks))
    if args.fit_transit:
        for i in range(len(peaks)):
            ###########################################################################
            #               Create the parameters                                     #
            ###########################################################################
            params = Parameters()
            params.add('t_zero', vary=True, value=time[peaks[i]],     min=time[peaks[i]] - 0.4, max=time[peaks[i]] + 0.4)
            params.add('radius_1',vary=True,   value=0.1, min=0.001, max=0.5)
            params.add('k',vary=True,   value=0.1, min=0.001, max=0.5)
            params.add('b',vary=True,   value=0.15, min=0.001, max=1)
            params.add('zp',vary=True,   value=0.0, min=-0.1, max=0.1)
            params.add('delta', value=0., vary=False , min=-0.5, max=1, expr='b-k') # constrain the limit b <= 1 + k

            theta_names = ['t_zero', 'radius_1', 'k', 'b', 'zp']
            mask = (time > (time[peaks[i]] - 0.75) ) & (time < (time[peaks[i]] + 0.75) )

            ###########################################################################
            #               Now solve                                                 #
            ###########################################################################
            mini = Minimizer(transit_model.get_residuals, params, fcn_args=(time[mask], mag[mask], mag_err[mask], theta_names, False ))
            lmfit_minimize_result = mini.minimize(method='differential_evolution')
            printfuncs.report_fit(lmfit_minimize_result, min_correl=0.5)
            
            ###########################################################################
            #               Now plot                                                  #
            ###########################################################################
            time_upsampled = np.linspace(np.min(time[mask]), np.max(time[mask]), 10000)
            model = transit_model.get_residuals(lmfit_minimize_result.params, time_upsampled,time_upsampled,time_upsampled,theta_names,  True)
            depth = np.max(model) - np.min(model)
            axs[i+idx_offset+1].plot(time_upsampled-time_offset, model, 'r', zorder=0)

            if args.cadence !=-1:
                transit_model.set_parameter('cadence', -1)
                model = transit_model.get_residuals(lmfit_minimize_result.params, time_upsampled,time_upsampled,time_upsampled,theta_names,  True)
                axs[i+idx_offset+1].plot(time_upsampled-time_offset, model, 'r--', zorder=0)


            width = transit_width(lmfit_minimize_result.params['radius_1'].value, lmfit_minimize_result.params['k'].value, lmfit_minimize_result.params['b'].value, P=args.fit_period)
            axs[i+idx_offset+1].set_xlim(lmfit_minimize_result.params['t_zero'].value-2*width-time_offset,lmfit_minimize_result.params['t_zero'].value+2*width-time_offset)


            # FIT_EPOCH,FIT_RADIUS_1,FIT_K,FIT_B,FIT_ZP,FIT_R2,FIT_DEPTH,FIT_WIDTH
            fit_pars.append([lmfit_minimize_result.params['t_zero'].value, lmfit_minimize_result.params['radius_1'].value, lmfit_minimize_result.params['k'].value, lmfit_minimize_result.params['b'].value, lmfit_minimize_result.params['zp'].value, args.R1*lmfit_minimize_result.params['k'].value, depth, width])

            R2 = lmfit_minimize_result.params['k'].value*args.R1
            axs[i+idx_offset+1].set_title('R2 = {:.2f} R'.format(R2) + r'$_{\odot}$' + '\n    = {:.2f} R'.format(R2*9.73115873) + r'$_{J}$' + '\nb = {:.2f}'.format(lmfit_minimize_result.params['b'].value), y=1-0.2)
            
            ###########################################################################
            #               Asteroid checking                                         #
            ###########################################################################
            # Asteroids are characterised by
            # 1. An increase in APX
            # 2. increase in SKYX
            # 3. Double peak in increasing sky apertures
            # Plan:
            # 1. plot AP mag in bottom left
            # 2. Plot sky annulus in bottom right
            if args.check_asteroid and args.fits:
                trimmed_asteroid_table = table_asteroid[(table_asteroid['BJD'] > (lmfit_minimize_result.params['t_zero'].value - 2*width)) & (table_asteroid['BJD'] < (lmfit_minimize_result.params['t_zero'].value + 2*width))]
                axin1 = axs[i+idx_offset+1].inset_axes([0.,0.,0.3,0.3])
                axin1.scatter(trimmed_asteroid_table['BJD'], trimmed_asteroid_table['AP{:}'.format(args.fitsapp)]/ np.median(trimmed_asteroid_table['AP{:}'.format(args.fitsapp)]), c='k', s=3)
                axin1.plot(trimmed_asteroid_table['BJD'], trimmed_asteroid_table['AP{:}'.format(args.fitsapp)]/ np.median(trimmed_asteroid_table['AP{:}'.format(args.fitsapp)]), 'k', linewidth=0.5, label='AP{:}'.format(args.fitsapp))
                axin1.scatter(trimmed_asteroid_table['BJD'], trimmed_asteroid_table['SKY{:}'.format(args.fitsapp)]/ np.median(trimmed_asteroid_table['SKY{:}'.format(args.fitsapp)]), c='y', s=3)
                axin1.plot(trimmed_asteroid_table['BJD'], trimmed_asteroid_table['SKY{:}'.format(args.fitsapp)]/ np.median(trimmed_asteroid_table['SKY{:}'.format(args.fitsapp)]), 'y', linewidth=0.5, label='SKY{:}'.format(args.fitsapp))
                axin1.set_xticks([], [])
                axin1.set_yticks([], [])
                axin1.legend(prop={"size":5})

                # look for peaks in Ap and Sky which we shouldent see
                y  = trimmed_asteroid_table['AP{:}'.format(args.fitsapp)]/ np.median(trimmed_asteroid_table['AP{:}'.format(args.fitsapp)])
                height = median_absolute_deviation(y)*3 + np.median(y)
                asteroids_peaks_ap, asteroids_meta = find_peaks(y, height=height, distance = 3)
                y  = trimmed_asteroid_table['SKY{:}'.format(args.fitsapp)]/ np.median(trimmed_asteroid_table['SKY{:}'.format(args.fitsapp)])
                height = median_absolute_deviation(y)*3 + np.median(y)
                asteroids_peaks_sky, asteroids_meta = find_peaks(y, height=height, distance = 5)
                if (len(asteroids_peaks_ap) > 0) or (len(asteroids_peaks_sky) > 0) : ASTEROID_CHECK_1 = 1
                if (len(asteroids_peaks_ap) > 0) and (len(asteroids_peaks_sky) > 0) : ASTEROID_CHECK_1 = 2
                if ASTEROID_CHECK_1 ==1 : axin1.set_title('Asteroid', color='orange')
                if ASTEROID_CHECK_1 ==2 : axin1.set_title('Asteroid', color='red')

                axin2 = axs[i+idx_offset+1].inset_axes([0.7,0.,0.3,0.5])
                axin2.set_xticks([], [])
                axin2.set_yticks([], [])

                asteroid_peak_count = np.zeros(6)
                for j in range(1,7):
                    y = trimmed_asteroid_table['SKY{:}'.format(j)]
                    y = 0.3*j + y / np.median(y[:10])
                    axin2.scatter(trimmed_asteroid_table['BJD'], y, c='y', s=3)
                    axin2.plot(trimmed_asteroid_table['BJD'],y, linewidth=0.5, label='SKY{:}'.format(j))
                    height = median_absolute_deviation(y)*3 + np.median(y)
                    asteroids_peaks, asteroids_meta = find_peaks(y, height=height, distance = 2)
                    if len(asteroids_peaks) > 0: axin2.scatter(trimmed_asteroid_table['BJD'][asteroids_peaks], y[asteroids_peaks], s=30, facecolors='none', edgecolors='r')
                    asteroid_peak_count[j-1] = len(asteroids_peaks)
                axin2.legend(prop={"size":5})

                # Now check the peaks and do a test
                if len(asteroids_peaks)>0:
                    if np.max(asteroids_peaks) > 0       : ASTEROID_CHECK_2 = 1
                    if np.sum(asteroid_peak_count>1) >=2 : ASTEROID_CHECK_2 = 2

                if ASTEROID_CHECK_2 ==1 : axin2.set_title('Asteroid', color='orange')
                if ASTEROID_CHECK_2 ==2 : axin2.set_title('Asteroid', color='red')


                # Now we need to check the X and Y positions in-transit, for asteroid checks later
                X[i] = np.median(trimmed_asteroid_table['X'])
                X[i], Xst[i] = np.median(trimmed_asteroid_table['X']), np.std(trimmed_asteroid_table['X'])
                Y[i], Yst[i] = np.median(trimmed_asteroid_table['Y']), np.std(trimmed_asteroid_table['Y'])




    title_text = '{:}\nra {:} dec {:}\nT = {:}\n'.format(args.name, args.ra, args.dec, args.mag) + 'R1 = {:.2f} R'.format(args.R1) +  r'$_{\odot}$'
    if JH_flag : title_text += ' [J-H]'

    axs[0].set_title( title_text)
    plt.tight_layout()
    #plt.savefig('{:}/{:}'.format(args.saveplace, args.filename.split('/')[-1].split('.')[0] + '_monofind.png'),  dpi=150)
    plt.savefig('{:}/{:}'.format(args.saveplace, args.name  + '_monofind.png'),  dpi=150)

    plt.close()

    
    if args.write_to_file != 'no':
        # Now save results to text file
        lock_file = '{:}/{:}'.format(args.saveplace, args.lock_file)
        savefile = '{:}/{:}'.format(args.saveplace, args.write_to_file)

        with open(lock_file, 'w') as ff:
            blocking_lock   = flock.Flock(ff, flock.LOCK_EX)
            with blocking_lock:
                write_str = ''
                for i in range(len(peaks)):
                    # First, peripherals
                    write_str += '{:},{:}'.format(args.name, i+1)

                    # Next write box fit
                    if args.fit_box : write_str += ',{:},{:},{:}'.format(*box_pars[i])
                    else            : write_str += ',-99,-99,-99'

                    # Next write fitted pars
                    if args.fit_transit : write_str += ',{:},{:},{:},{:},{:},{:},{:},{:},'.format(*fit_pars[i])
                    else                : write_str += ',-99,-99,-99,-99,-99,-99,-99,-99,' 

                    # Now add ra,dec, and mag, and asteroid checks
                    write_str += '{:},{:},{:},{:},{:},{:},{:},{:},{:},{:},{:}'.format(args.ra, args.dec, args.mag,args.R1, JH_flag,ASTEROID_CHECK_1, ASTEROID_CHECK_2, X[i], Xst[i], Y[i], Yst[i]) 

                    # add a new line
                    write_str += '\n'

                if not os.path.isfile(savefile):
                    f = open(savefile, 'a+')
                    f.write('NAME,PEAK,BOX_EPOCH,BOX_WIDTH,BOX_DEPTH,FIT_EPOCH,FIT_RADIUS_1,FIT_K,FIT_B,FIT_ZP,FIT_R2,FIT_DEPTH,FIT_WIDTH,RA,DEC,MAG,R1,JH_FLAG,ASTEROID_CHECK_1,ASTEROID_CHECK_2,X,Xe,Y,Ye\n')
                    f.close()

                f = open(savefile, 'a+')
                f.write(write_str)
                f.close()
    

'''
Pete wuestions
1. Aperture 2 is small
2. Annuls is too small (2 pixels) , use median instead of mean, clipped mean (report photutils) 
3. Top panel in ADU
4. BLS needs to knock out in-transit
5. Asteroid rejectin increase 12 , just distance cut
'''