#!/home/sam/anaconda3/bin/python

from multiprocessing import Pool
import os,sys, glob, numpy as np
from tqdm import tqdm
from contextlib import contextmanager
from collections import defaultdict
import pymysql
import argparse

@contextmanager
def open_db(host='ngtsdb', db='ngts_archive', user='u1870241', cur_class='list'):
    """
    Reusable database connection manager
    """
    if cur_class == 'list':
        with pymysql.connect(host=host,
                             db=db,
                             user=user) as cur:
            yield cur
    else:
        with pymysql.connect(host=host,
                             db=db,
                             user=user,
                             cursorclass=pymysql.cursors.DictCursor) as cur:
            yield cur 



def get_R1_from_tic(tic_id):
    qry = 'SELECT ra_deg, dec_deg, Tmag, rad, Jmag, Hmag from tic8 where tic_id={:};'.format(tic_id)

    with open_db(cur_class='list', db = 'catalogues') as cur: 
        cur.execute(qry) 
        results = cur.fetchall() 
        try: ra,dec, mag, R1, J, H =  results[0]
        except : return 
        
        try : float(ra)
        except : ra = 0.

        try : float(dec)
        except : dec = 0.

        try : float(mag)
        except : mag = 0.

        try : float(R1)
        except : R1 = -1.

        try : float(R1)
        except : R1 = -1.

        try : JH = float(J-H)
        except : JH = -1 

        return ra,dec, mag, R1 ,JH  


# This function takes a small list of 50000 and iterates over it 
parser = argparse.ArgumentParser('ngtsfit', description='monofindSGE')

parser.add_argument("small_list",
                    help='The filename of the star (time, mag, mag_err)')

parser.add_argument('-a', 
                '--threads',
                help='The number of threads to use [default 1]',
                default=10, type=int)

parser.add_argument('-b', 
                '--HOME_PATH',
                help='HOME_PATH',
                default='/tess/photometry/monotransit_bls', type=str)

parser.add_argument('-c', 
                '--lightcurve_file_path',
                help='lightcurve_file_path',
                default='/tess/photometry/tessFFIextract/lightcurves/S09', type=str)

parser.add_argument('-d', 
                '--monofind',
                help='lightcurve_file_path',
                default='/home/u1870241/anaconda3/bin/monofind', type=str)

parser.add_argument('-e', 
                '--write_to_file_monofind',
                help='write_to_file_monofind',
                default='MONOFIND_results.csv', type=str)

parser.add_argument('-f', 
                '--saveplace_monofind',
                help='saveplace_monofind',
                default= '/tess/photometry/monotransit_bls/monofind/S09', type=str)

parser.add_argument('-g', 
                '--monofind_mask',
                help='monofind_mask',
                default= '/tess/photometry/monotransit_bls/masks/S09_mask.fits', type=str)


app = 2 
monofind = '/home/u1870241/anaconda3/bin/monofind'
bls = '/home/u1870241/anaconda3/bin/bls'

def func(i): 
    cmd = '{:} {:} --fits --flatten --flatten_kernel 14 --fit_transit --threads 4 --saveplace {:}  --write_to_file {:} --name {:} --mask {:} --fitsapp {:} --ra {:} --dec {:} --mag {:}'.format(monofind, '{:}/TIC-{:}.fits'.format(args.lightcurve_file_path, tics[i]), args.saveplace_monofind , args.write_to_file_monofind, 'TIC-{:}'.format(tics[i]), args.monofind_mask, app, R1[i][0], R1[i][1], R1[i][2] )
    if (R1[i][3]==-1) and (R1[i][4]!=-1):
        cmd += ' --JH {:} --JHfile /home/u1870241/COLORS.csv'.format(R1[i][4]) # Use JHK colors
    else:
        cmd += ' --R1 {:}'.format(R1[i][3])
    os.system(cmd)


    cmd = '{:} {:} --fits --flatten --flatten_kernel 14 --saveplace {:}  --write_to_file {:} --name {:} --mask {:} --fitsapp {:} --ra {:} --dec {:} --mag {:} --sde 40 --fit'.format(bls, '{:}/TIC-{:}.fits'.format(args.lightcurve_file_path, tics[i]), args.saveplace_monofind , args.write_to_file_monofind + '_BLS', 'TIC-{:}'.format(tics[i]), args.monofind_mask, app, R1[i][0], R1[i][1], R1[i][2] )
    if (R1[i][3]==-1) and (R1[i][4]!=-1):
        cmd += ' --JH {:} --JHfile /home/u1870241/COLORS.csv'.format(R1[i][4]) # Use JHK colors
    else:
        cmd += ' --R1 {:}'.format(R1[i][3])
    os.system(cmd)
    #print(cmd)

if __name__=="__main__":
    # First, parse the args 
    args = parser.parse_args()

    # First load the sublist 
    f = open(args.small_list, 'r')
    tics = []

    while True:
        line = f.readline()
        if not line : break
        try : tics.append(int(line))
        except : pass

    R1 = np.zeros((len(tics), 5) )

    # ra,dec, mag, R1 
    print('Getting Radii')
    for i in tqdm(range(len(tics))):
        try : R1[i]  = get_R1_from_tic(tics[i])
        except : R1[i] = np.array([0.,0.,0.,-1.-1])

    # Now create the pool 
    print('Spawning pool')
    pool = Pool(args.threads)
    for _ in tqdm(pool.imap_unordered(func, range(len(tics))), total=len(tics)) : pass
    

