#!/home/sam/anaconda3/bin/python

###########################################################################
#                              Imports                                    #
###########################################################################

from bruce.binarystar.lc import lc, _lc
import emcee, corner, sys, os, numpy as np, math
import matplotlib.pyplot as plt 
import argparse 
from multiprocessing import Pool
from celerite.modeling import Model
from celerite import terms, GP
from scipy.stats import chisquare, sem
import matplotlib.cm as cm
import matplotlib.gridspec as gridspec
from multiprocessing import Pool
import numba
from scipy.optimize import minimize
from matplotlib.ticker import (MultipleLocator, FormatStrFormatter,
                               AutoMinorLocator)
np.warnings.filterwarnings('ignore')
import matplotlib
#matplotlib.use('Agg')
from lightkurve.lightcurve import TessLightCurve
from scipy.signal import find_peaks, medfilt
from scipy.optimize import curve_fit
from scipy.optimize import minimize
from astropy.table import Table, vstack
import emcee ,corner, time as time_func
import flock

from lmfit import minimize, Parameters, Minimizer, printfuncs, conf_interval
import lmfit 

from scipy.stats import median_absolute_deviation
from tqdm import tqdm 

plt.rcParams["font.family"] = "Times New Roman"
plt.rcParams.update({'font.size': 15})


###########################################################################
#                              Arg parser                                 #
###########################################################################
parser = argparse.ArgumentParser('monofindvet', description='Vet monofind results')
parser.add_argument("filename",
                    help='The filename of the binary star information')
parser.add_argument('-a', 
                '--sector',
                help='The filename of the binary star information',
                default=1, type=int)
parser.add_argument('-b', 
                '--chip_id',
                help='The chip_id',
                default = '1-1', type = str)

parser.add_argument('-c', 
                '--planet_radius',
                help='The planet radius to sort',
                default = 0.12, type = float)
parser.add_argument('-d', 
                '--eblm_radius',
                help='The EBLM radius to sort',
                default = 0.6, type = float)

parser.add_argument('--hist_epoch', action="store_true", default=False)
parser.add_argument('--radec', action="store_true", default=False)
parser.add_argument('--asteroid_check', action="store_true", default=False)
path_to_tssys = '/home/sam/Software/tssys'
parser.add_argument('--sort', action="store_true", default=False)

###########################################################################
#                              Load the datafile                          #
###########################################################################


if __name__=='__main__':
    # Parse the arguments
    args = parser.parse_args()

    ###########################################################################
    #                              Load the datafile                          #
    ###########################################################################
    t = Table.read(args.filename, format='csv')
    toffset = int(np.min(t['FIT_EPOCH']))
    histogram_mask = np.zeros(len(t), dtype = np.bool)
    asteroid_mask = t['ASTEROID_CHECK_2'] > 1
    
    ###########################################################################
    #                              Histogram                                  #
    ###########################################################################
    if args.hist_epoch:
        f1 = plt.figure(); ax1 = plt.gca()
        N, bins, patches = ax1.hist(t['FIT_EPOCH']-toffset, bins=50)
        MAD = median_absolute_deviation(N)
        ax1.set(title='Histogram of epochs', xlabel='BJD - {:}'.format(toffset), ylabel='Number')
        ax1.axhline(6*MAD, ls='--', c='k')
        histogram_idx = np.where((N > 6*MAD)==True)[0]
        for i in range(len(histogram_idx)) : 
            patches[histogram_idx[i]].set_facecolor('red')
            histogram_mask = histogram_mask |        ( ((t['FIT_EPOCH']-toffset) > bins[histogram_idx[i]])      & ((t['FIT_EPOCH']-toffset) < bins[histogram_idx[i]+1]) )
        f1.tight_layout()
        f1.savefig('MONOVET_HISTOGRAM.png')
        plt.close()

    ###########################################################################
    #                              RA dec distribution                        #
    ###########################################################################
    if args.radec:
        f2 = plt.figure(); ax2 = plt.gca()
        sc = ax2.scatter(t['X'][~histogram_mask], t['Y'][~histogram_mask], c=t['FIT_EPOCH'][~histogram_mask]-toffset, s=10)
        cbar = f2.colorbar(sc);  # show color scale
        cbar.set_label('BJD - {:}'.format(toffset))
        ax2.set(title='CCD position', xlabel='X', ylabel='Y')

        if args.asteroid_check:
            tssys = Table.read('{:}/release.merge'.format(path_to_tssys), format='ascii', header_start=None)
            # mask sector and chip
            camera, chip = int(args.chip_id[0]),  int(args.chip_id[2])
            tssys = tssys[ (tssys['col7']==args.sector) & (tssys['col8']==camera) & (tssys['col9']==chip)]


            i = 0
            asteroid_lightcurve = Table.read('{:}/lightcurves_spectra/{:}.lc'.format(path_to_tssys, tssys['col1'][i]), format='ascii')['col2', 'col3', 'col4', 'col5']
            print('Plotting asteroids')
            for i in tqdm(range(1, len(tssys))):
                asteroid_lightcurve = vstack((asteroid_lightcurve, Table.read('{:}/lightcurves_spectra/{:}.lc'.format(path_to_tssys, tssys['col1'][i]), format='ascii')['col2','col3', 'col4', 'col5']))

            min_mag = np.min(asteroid_lightcurve['col5'])
            max_mag = np.max(asteroid_lightcurve['col5'])
            alphas = np.array((asteroid_lightcurve['col5'] - min_mag) / (max_mag - min_mag))
            alphas = 1 - alphas # mag is fainter
            alphas*=0.04
            rgba_colors = np.zeros((len(alphas),4))
            rgba_colors[:,0] = 1.0
            rgba_colors[:, 3] = alphas
            #sc = ax2.scatter(asteroid_lightcurve['col3'], asteroid_lightcurve['col4'], c=rgba_colors, s = 0.1) 
            sc = ax2.scatter(asteroid_lightcurve['col3'], asteroid_lightcurve['col4'], c = asteroid_lightcurve['col5'] , s = 0.01, cmap='Reds_r', zorder=0) 
            cbar = f2.colorbar(sc);  # show color scale
            cbar.set_label('Tmag')

            # Now work out if each epoch had an asteroid nearby
            for i in tqdm(range(len(t))):
                # Get asteroid positions within 3 widths
                distances = np.hypot( asteroid_lightcurve['col3'] - t['X'][i], asteroid_lightcurve['col4'] - t['Y'][i] )
                asteroids_near_target = asteroid_lightcurve[(asteroid_lightcurve['col2'] > (t['FIT_EPOCH'][i] - 3*t['FIT_WIDTH'][i])) & (asteroid_lightcurve['col2'] < (t['FIT_EPOCH'][i] + 3*t['FIT_WIDTH'][i])) &  (distances < 6)]
                if len(asteroids_near_target) > 0:
                    # We have a hit, only plot if not cut by histogram
                    if not histogram_mask[i] :  ax2.scatter(t['X'][i], t['Y'][i], marker="2", color='r')
                    asteroid_mask[i] = True

            # Now mark off my asteroid hits 
            asteroid_mask = t['ASTEROID_CHECK_2']> 1
            ax2.scatter(t['X'][~histogram_mask & asteroid_mask], t['Y'][~histogram_mask & asteroid_mask], s=80, facecolors='none', edgecolors='b', alpha = 0.3)
        
        f2.tight_layout()
        f2.savefig('MONOVET_RADEC_ASTEROID.png')
        plt.close()


    if args.sort:
        # First, sort out the systmatics froom the histogram
        print('Sorting systematics [{:}]'.format(len(t[histogram_mask])))
        os.system('mkdir -p SYSTEMATICS')
        for i in tqdm(range(len(t[histogram_mask]))) : os.system('cp {:}_monofind.png SYSTEMATICS'.format(t[histogram_mask]['NAME'][i]))

        print('Sorting asteroids [{:}]'.format(len(t[~histogram_mask & asteroid_mask]) ))
        os.system('mkdir -p ASTEROIDS')
        for i in tqdm(range(len(t[~histogram_mask & asteroid_mask]))) : os.system('cp {:}_monofind.png ASTEROIDS'.format(t[~histogram_mask & asteroid_mask]['NAME'][i]))

        # Now sort good
        print('Sorting good objects [{:}]'.format(len(t[~histogram_mask & ~asteroid_mask])))
        os.system('mkdir -p PLANETS')
        os.system('mkdir -p EBLMs')
        os.system('mkdir -p EBs')

        for i in tqdm(range(len(t[~histogram_mask & ~asteroid_mask]))) : 
            R2 = t[~histogram_mask & ~asteroid_mask]['FIT_R2'][i]
            if R2 < args.planet_radius : os.system('cp {:}_monofind.png PLANETS'.format(t[~histogram_mask & ~asteroid_mask]['NAME'][i]))
            elif R2 < args.eblm_radius : os.system('cp {:}_monofind.png EBLMs'.format(t[~histogram_mask & ~asteroid_mask]['NAME'][i]))
            else                       : os.system('cp {:}_monofind.png EBs'.format(t[~histogram_mask & ~asteroid_mask]['NAME'][i]))