#!/home/sam/anaconda3/bin/python

import os,sys
from astropy.table import Table
import numpy as np
from astroquery.mast import Catalogs
from astroplan.plots import plot_finder_image
from astroplan import FixedTarget
import matplotlib.pyplot as plt
from astropy.coordinates import SkyCoord
import astropy.units as u
from matplotlib.patches import Circle


if __name__=='__main__':

    # First copy the tic fits from ngtshead
    print('Copying the lightcurve')
    os.system('scp u1870241@ngtshead.warwick.ac.uk:/tess/photometry/FFIlightcurves/TIC-{:}.fits .'.format(sys.argv[1]))
    print(sys.argv[1])

    # Now get the WASP lightcurve
    print('Searching WASP')
    os.system('tic2wasp {:}'.format(sys.argv[1]))

    t = Table.read('TIC-{:}.fits'.format(sys.argv[1]))
    nsectors = int((np.max(t['BJD']) - np.min(t['BJD'])) / 30.)
    print('Sectors : {:}'.format(nsectors))

    print('Queerying catalogue')
    catalog_data = Catalogs.query_object('TIC{:}'.format(sys.argv[1]), radius=0.0416667, catalog="TIC")
    catalog_data = catalog_data[catalog_data['Tmag'] < 16]
    i = 0

    print('-----------------------------------------------------')
    print('TIC-{:}'.format(sys.argv[1]))
    print('-----------------------------------------------------')
    print('Stellar parameters')
    print('\tTeff : {:.0f} +- {:.0f}'.format(catalog_data['Teff'][0], catalog_data['e_Teff'][0]))
    print('\tlogg : {:.2f} +- {:.2f}'.format(catalog_data['logg'][0], catalog_data['e_logg'][0]))
    print('\tMass : {:.2f} +- {:.2f}'.format(catalog_data['mass'][0], catalog_data['e_mass'][0]))
    print('\tRadius : {:.2f} +- {:.2f}'.format(catalog_data['rad'][0], catalog_data['e_rad'][0]))
    print('\tRho : {:.2f} +- {:.2f}'.format(catalog_data['rho'][0], catalog_data['e_rho'][0]))
    print('\tLum : {:.2f} +- {:.2f}'.format(catalog_data['lum'][0], catalog_data['e_lum'][0]))
    print('\traddflag : {:}'.format(catalog_data['raddflag'][0]))
    print('\twdflag : {:}'.format(catalog_data['wdflag'][0]))
    print('-----------------------------------------------------')
    print('Observational parameters')
    print('\tra : {:}'.format(catalog_data['ra'][0]))
    print('\tdec : {:}'.format(catalog_data['dec'][0]))

    mag_cols = []
    for i in range(len(catalog_data.colnames)):
        if (catalog_data.colnames[i][-3:]=='mag') and ('_' not in catalog_data.colnames[i]) : mag_cols.append(catalog_data.colnames[i])
    for i in range(len(mag_cols)) : 
        print('\t{:} : {:.3f}'.format(mag_cols[i], catalog_data[mag_cols[i]][0]))

    i = 0
    print('{:>10} : {:>10.3f}  [{:>6.2f}]'.format(catalog_data['ID'][i], catalog_data['Tmag'][i], catalog_data['dstArcSec'][i]))
    print('-----------------------------------------------------')
    flux_targ = 10**(-0.4*catalog_data['Tmag'][i])
    for i in range(1, len(catalog_data)):
        flux_comps = np.sum(10**(-0.4*catalog_data['Tmag'][1:i]))
        print('{:>10} : {:>10.3f} at {:>6.2f} [{:>6.2f} dil at AP{:}]'.format(catalog_data['ID'][i], catalog_data['Tmag'][i], catalog_data['dstArcSec'][i], flux_comps / flux_targ,   int(catalog_data['dstArcSec'][i]/21)))
    print('-----------------------------------------------------')

    # Now lets get the finder image
    c = SkyCoord(catalog_data['ra'][0], catalog_data['dec'][0], unit="deg")  # defaults to ICRS frame
    c = FixedTarget(coord=c, name='TIC-{:}'.format(sys.argv[1]))
    ax, hdu = plot_finder_image(c,fov_radius = 2*0.0416667*u.deg)

    # now plot circle apertures
    for i in range(1,7) : 
        c = Circle((catalog_data['ra'][0], catalog_data['dec'][0]), 0.00583333*i, edgecolor='r', facecolor='none', transform=ax.get_transform('fk5'), alpha = 0.3)
        ax.add_patch(c)
    for i in range(1, len(catalog_data)):
        c = Circle((catalog_data['ra'][i], catalog_data['dec'][i]), 0.001, edgecolor='b', facecolor='none', transform=ax.get_transform('fk5'), alpha = 1)
        ax.add_patch(c)

    plt.savefig('TIC-{:}_field.png'.format(sys.argv[1]))
    plt.close()